/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Link } from 'react-router-dom';
import { styled } from '@mui/material/styles';
import Card4 from 'src/components/Card4/Card4';
import LoginButtonFrame from 'src/components/LoginButtonFrame/LoginButtonFrame';

const MsgApp21 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `932px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const GridFrame = styled('div')({
  borderRadius: `0px`,
  display: `grid`,
  position: `relative`,
  isolation: `isolate`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100%`,
  margin: `0px`,
  overflow: `hidden`,
  height: `auto`,
  gridTemplateColumns: `repeat(auto-fit, minmax(430px, 1fr))`,
  columnGap: `10px`,
  rowGap: `10px`,
});

const Card41 = styled(Card4)(({ theme }) => ({
  width: `430px`,
  margin: `0px`,
}));

const LoginButtonFrame1 = styled(LoginButtonFrame)(({ theme }) => ({
  width: `430px`,
  position: `sticky`,
  left: `0px`,
  top: `776px`,
  bottom: `0`,
  zIndex: `3000`,
}));

const InternalLink = styled(Link)({
  width: `430px`,
  textDecoration: `none`,
});

function MsgApp2(props) {
  return (
    <MsgApp21 className={props.className}>
      <GridFrame>
        {props.posts &&
          props.posts.map((mypost, index) => {
            return <Card41 key={index} post={mypost} />;
          })}
      </GridFrame>
      <InternalLink to="/login">
        <LoginButtonFrame1 />
      </InternalLink>
    </MsgApp21>
  );
}

export default MsgApp2;
